### ISSUE TITLE
block in replace_gem': Please install the sqlite3 adapter: `gem install activerecord-sqlite3-adapter

### ISSUE THREAD

**Issue by hr1383** [thiagopradi/octopus_sharding_example#5]
Hi ,

 I am trying to use this gem and after adding and installing the gem , i try to do rails s and get the following error 

block in replace_gem': Please install the sqlite3 adapter: `gem install activerecord-sqlite3-adapter` (sqlite3 is not part of the bundle. Add it to Gemfile.) (LoadError)
    from /Users/hrastogi/.rvm/gems/ruby-1.9.2-p320/gems/activerecord-3.2.12/lib/active_record/connection_adapters/sqlite3_adapter.rb:3:in `<top (required)>'
    from /Users/hrastogi/.rvm/gems/ruby-1.9.2-p320/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:251:in`require'
    from /Users/hrastogi/.rvm/gems/ruby-1.9.2-p320/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:251:in `block in require'
    from /Users/hrastogi/.rvm/gems/ruby-1.9.2-p320/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:236:in`load_dependency'
    from /Users/hrastogi/.rvm/gems/ruby-1.9.2-p320/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:251:in `require'

Whats interesting is that i am using mysql and tried with mysql2 also .

GIT
  remote: git://github.com/tchandy/octopus.git
  revision: f74656eae32ba4fe698d9a8b15f6344a6f9d4ebe
  specs:
    ar-octopus (0.5.0beta)
      activerecord (>= 2.3.0)
      activesupport (>= 2.3.0)

GEM
  remote: https://rubygems.org/
  specs:
    actionmailer (3.2.12)
      actionpack (= 3.2.12)
      mail (~> 2.4.4)
    actionpack (3.2.12)
      activemodel (= 3.2.12)
      activesupport (= 3.2.12)
      builder (~> 3.0.0)
      erubis (~> 2.7.0)
      journey (~> 1.0.4)
      rack (~> 1.4.5)
      rack-cache (~> 1.2)
      rack-test (~> 0.6.1)
      sprockets (~> 2.2.1)
    activemodel (3.2.12)
      activesupport (= 3.2.12)
      builder (~> 3.0.0)
    activerecord (3.2.12)
      activemodel (= 3.2.12)
      activesupport (= 3.2.12)
      arel (~> 3.0.2)
      tzinfo (~> 0.3.29)
    activeresource (3.2.12)
      activemodel (= 3.2.12)
      activesupport (= 3.2.12)
    activesupport (3.2.12)
      i18n (~> 0.6)
      multi_json (~> 1.0)
    arel (3.0.2)
    builder (3.0.4)
    coffee-rails (3.2.2)
      coffee-script (>= 2.2.0)
      railties (~> 3.2.0)
    coffee-script (2.2.0)
      coffee-script-source
      execjs
    coffee-script-source (1.6.1)
    erubis (2.7.0)
    execjs (1.4.0)
      multi_json (~> 1.0)
    hike (1.2.1)
    i18n (0.6.4)
    journey (1.0.4)
    jquery-rails (2.2.1)
      railties (>= 3.0, < 5.0)
      thor (>= 0.14, < 2.0)
    json (1.7.7)
    mail (2.4.4)
      i18n (>= 0.4.0)
      mime-types (~> 1.16)
      treetop (~> 1.4.8)
    mime-types (1.21)
    multi_json (1.6.1)
    mysql2 (0.3.11)
    polyglot (0.3.3)
    rack (1.4.5)
    rack-cache (1.2)
      rack (>= 0.4)
    rack-ssl (1.3.3)
      rack
    rack-test (0.6.2)
      rack (>= 1.0)
    rails (3.2.12)
      actionmailer (= 3.2.12)
      actionpack (= 3.2.12)
      activerecord (= 3.2.12)
      activeresource (= 3.2.12)
      activesupport (= 3.2.12)
      bundler (~> 1.0)
      railties (= 3.2.12)
    railties (3.2.12)
      actionpack (= 3.2.12)
      activesupport (= 3.2.12)
      rack-ssl (~> 1.3.2)
      rake (>= 0.8.7)
      rdoc (~> 3.4)
      thor (>= 0.14.6, < 2.0)
    rake (10.0.3)
    rdoc (3.12.2)
      json (~> 1.4)
    sass (3.2.7)
    sass-rails (3.2.6)
      railties (~> 3.2.0)
      sass (>= 3.1.10)
      tilt (~> 1.3)
    sprockets (2.2.2)
      hike (~> 1.2)
      multi_json (~> 1.0)
      rack (~> 1.0)
      tilt (~> 1.1, != 1.3.0)
    thor (0.17.0)
    tilt (1.3.5)
    treetop (1.4.12)
      polyglot
      polyglot (>= 0.3.1)
    tzinfo (0.3.37)
    uglifier (1.3.0)
      execjs (>= 0.3.0)
      multi_json (~> 1.0, >= 1.0.2)

PLATFORMS
  ruby

DEPENDENCIES
  ar-octopus!
  coffee-rails (~> 3.2.1)
  jquery-rails
  mysql2
  rails (= 3.2.12)
  sass-rails (~> 3.2.3)
  uglifier (>= 1.0.3)

I have added it to a repo 
https://github.com/hr1383/myproj1

**Comment by hr1383** [comment]
ok my bad, i didnt update the database.yml .
